CUDA_VISIBLE_DEVICES=0 python src/pretrain.py \
--data_dir data/sports \
--model_name t5-small \
--batch_size 64 \
--cuda \
--checkpoint out/sports/ \
--epochs 30 \
--prompt_num 20 \
--prompt_length 3 \
--num_heads 4 \
--seed 1 \
--wandb_name sports_20x3_module_multihead_4_seed_1 \
--out_file sports_20x3_module_multihead_4_seed_1.pt
